title: Abhishek Mishra
logo: "images/Profile Pic.jpeg"
description: >
  Data Analyst with a love of problem-solving and empowering others. My technical expertise in SQL, Excel, Microsoft Power BI, and Python enables me to bridge the gap between complex data and clear, actionable insights. But beyond the technical skills, I believe in the human element of data analysis. My strong communication skills allow me to collaborate effectively and translate insights into meaningful, actionable stories that guide positive business decisions.
  
  View My Profile On:
  [LinkedIn](https://www.linkedin.com/in/abhishekmishra3/) | [Github](https://github.com/abhishekmishra8/)

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
