title: Abhishek Mishra
logo: "images/Profile Pic.jpeg"
description: >
  Data Analyst with a love of problem-solving and empowering others. My strong communication skills along with my technicals skills in SQL, Excel, Microsoft Power BI and Python allow me to transform data into impactful insights that lead to the best business decisions.

  <br><br>
  View My Profile On:
  <a href="https://www.linkedin.com/in/abhishekmishra3/">LinkedIn</a> | 
  <a href="https://github.com/abhishekmishra8/">Github</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
