title: Abhishek Mishra # your name (or website title) here
logo: "images/Profile Pic.jpeg" #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a love of helping others and problem solving. My strong communication 
  skills along with my technicals skills in SQL, Excel and Tableau allow me 
  to transform data into impactful insights that lead to the best business decisions.

  <br><br>
  View My Profile On:
  <a href="https://www.linkedin.com/in/abhishekmishra3/">LinkedIn</a> | 
  <a href="https://github.com/abhishekmishra8/">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
